### ISSUE TITLE
XQuery: Runtime Exception

### ISSUE THREAD

**Issue by ChristianGruen** [BaseXdb/basex#1094]
**Query:**

```xquery
let $a := <a/>
return 'bar' ! . ! $a
```

**Result:**

```
java.lang.RuntimeException: $a_0
	at org.basex.util.Util.notExpected(Util.java:60)
	at org.basex.query.var.QueryStack.pos(QueryStack.java:85)
	at org.basex.query.var.QueryStack.get(QueryStack.java:95)
	at org.basex.query.QueryContext.get(QueryContext.java:758)
	at org.basex.query.var.VarRef.iter(VarRef.java:56)
	at org.basex.query.QueryContext.iter(QueryContext.java:404)
	at org.basex.query.expr.IterMap$1.next(IterMap.java:58)
	at org.basex.query.MainModule$1.next(MainModule.java:118)
	at org.basex.query.QueryContext.execute(QueryContext.java:629)
	at org.basex.query.QueryProcessor.execute(QueryProcessor.java:98)
```

**Comment by LeoWoerteler** [comment]
`SimpleMap#count(Var)` and `SimpleMap#removable(Var)` expect at most one `!` and ignore the rest.

**Comment by ChristianGruen** [comment]
Exactly… I'm fixing this right one. Thanks.
