### ISSUE TITLE
Function Coercion for Arrays etc.

### ISSUE THREAD

**Issue by LeoWoerteler** [BaseXdb/basex#1106]
## Query:
```xquery
declare function local:foo(
  $f as function(xs:integer) as xs:string
) {
  $f(1), $f(3)
};
local:foo(['foo', error#0, 'bar'])
```
## Expected:
`'foo', 'bar'`
## Result:
    org.basex.query.QueryException: Cannot cast array(*) to function(xs:integer) as xs:string: ["foo", (: fn:error#0 :) functio....
    	at org.basex.query.QueryError.get(QueryError.java:1296)
    	at org.basex.query.QueryError.castError(QueryError.java:1466)
    	at org.basex.query.value.array.Array.coerceTo(Array.java:256)
    	at org.basex.query.value.type.SeqType.promote(SeqType.java:493)
    	at org.basex.query.value.type.SeqType.promote(SeqType.java:455)
    	at org.basex.query.var.Var.checkType(Var.java:161)
    	at org.basex.query.expr.gflwor.Let.optimize(Let.java:103)

Relevant part of the [spec](http://www.w3.org/TR/xquery-31/#id-function-coercion):

> Definition: **Function coercion** wraps a [function](http://www.w3.org/TR/xpath-datamodel-31/#dt-function-item)<sup>DM31</sup> in a new function with signature the same as the expected type. This effectively delays the checking of the argument and return types until the function is invoked.

**Comment by ChristianGruen** [comment]
Fixed
