### ISSUE TITLE
XQuery, GFLWOR: ConcurrentModificationException

### ISSUE THREAD

**Issue by ChristianGruen** [BaseXdb/basex#1150]
XQuery:

```xquery
let $x := "does-not-exist.xml"
for $x in doc($x)
let $x := count($x)
return $x
```

Stack Trace:

```
java.util.ConcurrentModificationException
  at java.util.LinkedList$ListItr.checkForComodification(Unknown Source)
  at java.util.LinkedList$ListItr.remove(Unknown Source)
  at org.basex.query.expr.gflwor.GFLWOR.inlineLets(GFLWOR.java:377)
  at org.basex.query.expr.gflwor.GFLWOR.optimize(GFLWOR.java:145)
  at org.basex.query.expr.gflwor.GFLWOR.compile(GFLWOR.java:117)
  at org.basex.query.MainModule.compile(MainModule.java:74)
  at org.basex.query.QueryCompiler.compile(QueryCompiler.java:113)
  at org.basex.query.QueryCompiler.compile(QueryCompiler.java:104)
  at org.basex.query.QueryContext.analyze(QueryContext.java:330)
  at org.basex.query.QueryContext.compile(QueryContext.java:319)
  at org.basex.query.QueryProcessor.compile(QueryProcessor.java:69)
  at org.basex.core.cmd.AQuery.query(AQuery.java:75)
```

**Comment by ChristianGruen** [comment]
Java example causing the same exception:

```java
public static void main(String... args) {
  List<String> list = new ArrayList<>();
  list.add("1");

  Iterator<String> it = list.iterator();
  while(it.hasNext()) {
    String string = it.next();
    list.remove(string);
  }
}
```
