### ISSUE TITLE
Error during REPLACE

### ISSUE THREAD

**Issue by egor-bayandin** [BaseXdb/basex#1182]
Hi,
 I got following error during try to add new XML without duplication using REPLACE * /opt/xml command

> replace * /opt/xml
Improper use? Potential bug? Your feedback is welcome:
Contact: basex-talk@mailman.uni-konstanz.de
Version: BaseX 8.2.3
Java: Oracle Corporation, 1.7.0_67
OS: Linux, amd64
Stack Trace: 
java.lang.ArrayIndexOutOfBoundsException: 0
	at org.basex.util.Num.length(Num.java:132)
	at org.basex.util.Compress.unpack(Compress.java:99)
	at org.basex.data.DiskData.txt(DiskData.java:300)
	at org.basex.data.DiskData.text(DiskData.java:267)
	at org.basex.index.resource.Docs.insert(Docs.java:164)
	at org.basex.index.resource.Resources.insert(Resources.java:68)
	at org.basex.data.Data.insert(Data.java:730)
	at org.basex.query.up.atomic.Insert.apply(Insert.java:44)
	at org.basex.query.up.atomic.AtomicUpdateCache.applyUpdates(AtomicUpdateCache.java:297)
	at org.basex.query.up.atomic.AtomicUpdateCache.execute(AtomicUpdateCache.java:281)
	at org.basex.core.cmd.Replace.replace(Replace.java:106)
	at org.basex.core.cmd.Replace.run(Replace.java:57)
	at org.basex.core.Command.run(Command.java:398)
	at org.basex.core.Command.execute(Command.java:100)
	at org.basex.server.ClientListener.run(ClientListener.java:136)

**Comment by ChristianGruen** [comment]
We need more information to fix this. Could you please provide us with concrete steps to reproduce the problem?

**Comment by egor-bayandin** [comment]
1. Create DB with ~150000 XML files with attribute index, total DB size ~5Gb
2. Try to replace/add about 50000 XML files with command "replace * /opt/xml"

**Comment by ChristianGruen** [comment]
Hm, that's too general; we have numerous BaseX database instances of that size without encountering such problems. I'm closing this for now. Thanks for your feedback, though; I invite you to write to the mailing list once this is more easily reproducible.
