### ISSUE TITLE
WebDAV: Non-ASCII characters

### ISSUE THREAD

**Issue by ChristianGruen** [BaseXdb/basex#1184]
https://www.mail-archive.com/basex-talk@mailman.uni-konstanz.de/msg06891.html

```
dav:/webdav/> ls
Listing collection `/webdav/': collection is empty.

dav:/webdav/> mkcol üöäß
Creating `üöäß': succeeded.

dav:/webdav/> ls
Listing collection `/webdav/': succeeded.
Coll:   uoas

and using Python 2.7 (using pyfilesystem API).
```

Moreover, an error is raised if a directory with non-ASCII characters is created on top-level:

```
[qtp716083600-16] WARN org.eclipse.jetty.server.AbstractHttpConnection - Failed UTF-8 decode for request path, trying ISO-8859-1
[qtp716083600-16] INFO com.bradmcevoy.http.HttpManager - MKCOL :: http://localhost:8984/webdav/%e4 - http://localhost:8984/webdav/%e4
[qtp716083600-16] WARN com.bradmcevoy.http.StandardFilter - BadRequestException: Name '' is invalid.
com.bradmcevoy.http.exceptions.BadRequestException
        at org.basex.http.webdav.BXCode.eval(BXCode.java:43)
        at org.basex.http.webdav.BXRoot.createCollection(BXRoot.java:79)
        at org.basex.http.webdav.BXRoot.createCollection(BXRoot.java:1)
        at com.bradmcevoy.http.webdav.MkColHandler$DefaultCollectionResourceCreator.createResource(MkColHandler.java:171)
        at com.bradmcevoy.http.webdav.MkColHandler.processMakeCol(MkColHandler.java:152)
        at com.bradmcevoy.http.webdav.MkColHandler.process(MkColHandler.java:102)
        at com.bradmcevoy.http.webdav.MkColHandler.process(MkColHandler.java:59)
        at com.bradmcevoy.http.StandardFilter.process(StandardFilter.java:52)
        at com.bradmcevoy.http.FilterChain.process(FilterChain.java:40)
        at com.bradmcevoy.http.HttpManager.process(HttpManager.java:228)
        at org.basex.http.webdav.WebDAVServlet.run(WebDAVServlet.java:43)
        at org.basex.http.BaseXServlet.service(BaseXServlet.java:64)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
```

**Comment by zopyx** [comment]
Seems to be fixed and working in latest 8.3 build (26-8-2015) or later
