### ISSUE TITLE
Race conditions in 8.3 beta 

### ISSUE THREAD

**Issue by zopyx** [BaseXdb/basex#1188]
As part of my cross-db tests of XML Director I see sporadic failures within
the test fixture of my tests. In particular I frequently see the following error
while checking for the existence of the test director and then trying to remove it.

On the client side there is no other code accessing or blocking BaseX in someway since the
tests are executed in sequential order, no other processes involved, everything is run
inside a single thread.

I have not seen this issue with older versions of BaseX

[qtp209556486-16] INFO com.bradmcevoy.http.HttpManager - PROPFIND :: http://localhost:8984/webdav/ - http://localhost:8984/webdav/
=> http://localhost:8984/webdav/testing-54d38918-cb84-482e-a2fc-080daa43cd6c
[qtp209556486-18] INFO com.bradmcevoy.http.HttpManager - PROPFIND :: http://localhost:8984/webdav/testing-54d38918-cb84-482e-a2fc-080daa43cd6c - http://localhost:8984/webdav/testing-54d38918-cb84-482e-a2fc-080daa43cd6c
=> http://localhost:8984/webdav/testing-54d38918-cb84-482e-a2fc-080daa43cd6c
[qtp209556486-16] INFO com.bradmcevoy.http.HttpManager - PROPFIND :: http://localhost:8984/webdav/testing-54d38918-cb84-482e-a2fc-080daa43cd6c - http://localhost:8984/webdav/testing-54d38918-cb84-482e-a2fc-080daa43cd6c
=> http://localhost:8984/webdav/testing-54d38918-cb84-482e-a2fc-080daa43cd6c
[qtp209556486-18] INFO com.bradmcevoy.http.HttpManager - DELETE :: http://localhost:8984/webdav/testing-54d38918-cb84-482e-a2fc-080daa43cd6c - http://localhost:8984/webdav/testing-54d38918-cb84-482e-a2fc-080daa43cd6c
[qtp209556486-18] WARN com.bradmcevoy.http.StandardFilter - BadRequestException: Database 'testing-54d38918-cb84-482e-a2fc-080daa43cd6c' is currently opened by another process.

com.bradmcevoy.http.exceptions.BadRequestException
        at org.basex.http.webdav.BXCode.eval(BXCode.java:43)
        at org.basex.http.webdav.BXAbstractResource.delete(BXAbstractResource.java:103)
        at com.bradmcevoy.http.DeleteHelperImpl.delete(DeleteHelperImpl.java:93)
        at com.bradmcevoy.http.http11.DeleteHandler.processExistingResource(DeleteHandler.java:86)
        at com.bradmcevoy.http.ResourceHandlerHelper.processResource(ResourceHandlerHelper.java:149)
        at com.bradmcevoy.http.ResourceHandlerHelper.processResource(ResourceHandlerHelper.java:95)
        at com.bradmcevoy.http.http11.DeleteHandler.processResource(DeleteHandler.java:71)
        at com.bradmcevoy.http.ResourceHandlerHelper.process(ResourceHandlerHelper.java:91)
        at com.bradmcevoy.http.http11.DeleteHandler.process(DeleteHandler.java:66)
        at com.bradmcevoy.http.StandardFilter.process(StandardFilter.java:52)
        at com.bradmcevoy.http.FilterChain.process(FilterChain.java:40)
        at com.bradmcevoy.http.HttpManager.process(HttpManager.java:228)
        at org.basex.http.webdav.WebDAVServlet.run(WebDAVServlet.java:43)
        at org.basex.http.BaseXServlet.service(BaseXServlet.java:64)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:684)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:503)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:429)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
        at org.eclipse.jetty.server.Server.handle(Server.java:370)
        at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)
        at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:971)
        at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:1033)
        at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:644)
        at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
        at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:696)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:53)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
        at java.lang.Thread.run(Unknown Source)
=> http://localhost:8984/webdav/

**Comment by ChristianGruen** [comment]
I didn't manage to reproduce something similar so far. Do you think there's a chance to provide us with a self-contained test?

**Comment by ChristianGruen** [comment]
Based on some (unconfirmed) assumptions, I have created a [new snapshot](http://files.basex.org/releases/latest/). Could you please test it and give us some feedback?

**Comment by zopyx** [comment]
I can no longer reproduce the behavior with the newest snapshot.

2015-09-15 18:59 GMT+02:00 Christian Gruen <notifications@github.com>:

**Comment by ChristianGruen** [comment]
Thanks for the feedback.
