### ISSUE TITLE
Context creation fails in JBoss

### ISSUE THREAD

**Issue by croizier** [BaseXdb/basex#1213]
We are unable to perform local queries inside JBoss, not even creating a new Context.
```
java.nio.file.FileSystemNotFoundException: Provider "vfs" not installed
	at java.nio.file.Paths.get(Paths.java:147)
	at org.basex.util.Prop.homePath(Prop.java:150)
	at org.basex.util.Prop.<clinit>(Prop.java:99)
	at org.basex.core.StaticOptions.<clinit>(StaticOptions.java:18)
	at org.basex.core.Context.<init>(Context.java:76)
	at org.basex.core.Context.<init>(Context.java:68)
```
This may be related to [this SO issue](http://stackoverflow.com/q/27001497/3478605).

**Comment by ChristianGruen** [comment]
I would be interested to learn when BaseX is called (which will always create a new Context instance). Can you find a full stack trace somewhere around?

**Comment by ChristianGruen** [comment]
One more note: In [Prop.java](https://github.com/BaseXdb/basex/blob/master/basex-core/src/main/java/org/basex/util/Prop.java#L150), you will see that the output is a purely informational: If file resolution fails, the default directory will be used as "home directory".

If you cannot run queries, this should have another reason. Could you possibly give us some more hints?

**Comment by croizier** [comment]
In this case, we just instanciate a Context with `new Context()` in a ServletContextListener initializer.
Here is the full stacktrace.
```
java.nio.file.FileSystemNotFoundException: Provider "vfs" not installed
	at java.nio.file.Paths.get(Paths.java:147)
	at org.basex.util.Prop.homePath(Prop.java:150)
	at org.basex.util.Prop.<clinit>(Prop.java:99)
	at org.basex.core.StaticOptions.<clinit>(StaticOptions.java:18)
	at org.basex.core.Context.<init>(Context.java:76)
	at mydomain.LocatorManager.contextInitialized(LocatorManager.java:37)
	at org.apache.catalina.core.StandardContext.contextListenerStart(StandardContext.java:3339)
	at org.apache.catalina.core.StandardContext.start(StandardContext.java:3780)
	at org.jboss.as.web.deployment.WebDeploymentService.doStart(WebDeploymentService.java:163)
	at org.jboss.as.web.deployment.WebDeploymentService.access$000(WebDeploymentService.java:61)
	at org.jboss.as.web.deployment.WebDeploymentService$1.run(WebDeploymentService.java:96)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jboss.threads.JBossThread.run(JBossThread.java:122)
```

**Comment by ChristianGruen** [comment]
Thanks. As indicated before, I guess the stack trace may safely be ignored (we may move it to the database logs in a future version). Any more info on the failure of query execution is welcome.

**Comment by croizier** [comment]
Indeed, the query is run correctly after the stacktrace!
