### ISSUE TITLE
ArrayIndexOutOfBoundsException in org.basex.util.Version

### ISSUE THREAD

**Issue by Tails** [BaseXdb/basex#1238]
I had a batch process running that inserted a lot of XML until the disk was full and Java started throwing exceptions. Now when I start the server I get this error. Any idea on what could resolve this? It also comes up at every query making the database unusable.

```
xmldatabase_1 | SET AUTOFLUSH true
xmldatabase_1 | SET WRITEBACK true
xmldatabase_1 | SET MAINMEM false
xmldatabase_1 | /srv/.basex: writing new configuration file.
xmldatabase_1 | Improper use? Potential bug? Your feedback is welcome:
xmldatabase_1 | Contact: basex-talk@mailman.uni-konstanz.de
xmldatabase_1 | Version: BaseX 8.4 beta 5687c30
xmldatabase_1 | Java: Oracle Corporation, 1.8.0_66-internal
xmldatabase_1 | OS: Linux, amd64
xmldatabase_1 | Stack Trace: 
xmldatabase_1 | java.lang.ArrayIndexOutOfBoundsException: 0
xmldatabase_1 | 	at org.basex.util.Version.<init>(Version.java:33)
xmldatabase_1 | 	at org.basex.util.Version.<init>(Version.java:24)
xmldatabase_1 | 	at org.basex.data.MetaData.read(MetaData.java:338)
xmldatabase_1 | 	at org.basex.data.DiskData.<init>(DiskData.java:56)
xmldatabase_1 | 	at org.basex.core.cmd.Open.open(Open.java:99)
xmldatabase_1 | 	at org.basex.core.cmd.Open.run(Open.java:48)
xmldatabase_1 | 	at org.basex.core.Command.run(Command.java:398)
xmldatabase_1 | 	at org.basex.core.Command.run(Command.java:150)
xmldatabase_1 | 	at org.basex.core.cmd.Check.run(Check.java:46)
xmldatabase_1 | 	at org.basex.core.Command.run(Command.java:398)
xmldatabase_1 | 	at org.basex.core.Command.execute(Command.java:100)
xmldatabase_1 | 	at org.basex.api.client.LocalSession.execute(LocalSession.java:132)
xmldatabase_1 | 	at org.basex.api.client.Session.execute(Session.java:36)
xmldatabase_1 | 	at org.basex.core.CLI.execute(CLI.java:103)
xmldatabase_1 | 	at org.basex.core.CLI.execute(CLI.java:87)
xmldatabase_1 | 	at org.basex.core.CLI.execute(CLI.java:74)
xmldatabase_1 | 	at org.basex.BaseX.<init>(BaseX.java:86)
xmldatabase_1 | 	at org.basex.BaseX.main(BaseX.java:42)
xmldatabase_1 | LOG: false
xmldatabase_1 | DEBUG: true
xmldatabase_1 | Creating Database...
xmldatabase_1 | . 7.05 ms (10321 KB)
xmldatabase_1 | Creating /srv/BaseXWeb/WEB-INF/web.xml
xmldatabase_1 | Creating /srv/BaseXWeb/WEB-INF/jetty.xml
xmldatabase_1 | BaseX 8.4 beta 5687c30 [HTTP Server]
xmldatabase_1 | [main] INFO org.eclipse.jetty.server.Server - jetty-8.1.18.v20150929
xmldatabase_1 | [main] INFO org.eclipse.jetty.webapp.StandardDescriptorProcessor - NO JSP Support for /, did not find org.apache.jasper.servlet.JspServlet
xmldatabase_1 | LOG: false
xmldatabase_1 | WEBPATH: /srv/BaseXWeb
xmldatabase_1 | DEBUG: true
xmldatabase_1 | Server was started (port: 1984).
xmldatabase_1 | [main] INFO org.eclipse.jetty.server.AbstractConnector - Started SelectChannelConnector@0.0.0.0:8984
xmldatabase_1 | HTTP Server was started (port: 8984).
```

**Comment by ChristianGruen** [comment]
Hardly possible to "fix" this if your disk was full. Probably one of the databases has gone corrupt?

**Comment by Tails** [comment]
Thank you for the quick reply :)

It seems so. So there are no validation functions to salvage any of it?

**Comment by ChristianGruen** [comment]
And thanks as well for reporting it. I think ’ll catch errors of this kind and return a more helpful error message.

**Comment by ChristianGruen** [comment]
> It seems so. So there are no validation functions to salvage any of it?

The [INSPECT](http://docs.basex.org/wiki/Commands#INSPECT) command can be run to check if a specific database is ok. But in most cases, it’s difficult to restore data of corrupt databases, because there is a wide variety of reasons what could have gone wrong.

**Comment by Tails** [comment]
I see, I tried the INSPECT but it couldn't get through the error. Ran the batch again after increasing disk size, no problem. Very happy with it. Thanks for your help!
