### ISSUE TITLE
Copying from Emacs to BaseX issues on Linux

### ISSUE THREAD

**Issue by ejbs** [BaseXdb/basex#1277]
Hi!

When I copy something in an Emacs buffer (w/ M-w) I can usually paste it into whatever program I want to but this is not possible in BaseX, instead I had to go through a workaround where I paste what I copied from Emacs into gedit first and then copy from gedit into BaseX.

I use Ubuntu 14.04.4 and BaseX version is 8.4.1 (this bug was present in version 7 too)

**Comment by ejbs** [comment]
Note that the opposite (copying from BaseX to emacs) poses no problem.

**Comment by ChristianGruen** [comment]
Could you please download the [latest snapshot](http://files.basex.org/releases/latest/), start the GUI in debugging mode (using `basexgui -d`) and report back which output you get on command-line? Thanks in advance.

**Comment by ejbs** [comment]
I ran it as java -jar BaseX842-20160321.145321.jar -d

I got the following stack trace (I'm not sure if it's related but since it mentions the clipboard I guess so):
```
java.io.IOException: Owner failed to convert data
	at sun.awt.X11.XSelection.validateDataGetter(XSelection.java:444)
	at sun.awt.X11.XSelection.getData(XSelection.java:305)
	at sun.awt.X11.XClipboard.getClipboardData(XClipboard.java:120)
	at sun.awt.datatransfer.ClipboardTransferable.fetchOneFlavor(ClipboardTransferable.java:117)
	at sun.awt.datatransfer.ClipboardTransferable.<init>(ClipboardTransferable.java:97)
	at sun.awt.X11.XClipboard.getContents(XClipboard.java:106)
	at org.basex.gui.text.TextPanel.clip(TextPanel.java:739)
	at org.basex.gui.text.TextPanel.access$5(TextPanel.java:736)
	at org.basex.gui.text.TextPanel$PasteCmd.enabled(TextPanel.java:873)
	at org.basex.gui.GUIPopupCmd.execute(GUIPopupCmd.java:34)
	at org.basex.gui.layout.BaseXPopup$2.keyPressed(BaseXPopup.java:66)
	at java.awt.AWTEventMulticaster.keyPressed(AWTEventMulticaster.java:250)
	at java.awt.Component.processKeyEvent(Component.java:6474)
	at javax.swing.JComponent.processKeyEvent(JComponent.java:2820)
	at java.awt.Component.processEvent(Component.java:6293)
	at java.awt.Container.processEvent(Container.java:2229)
	at java.awt.Component.dispatchEventImpl(Component.java:4872)
	at java.awt.Container.dispatchEventImpl(Container.java:2287)
	at java.awt.Component.dispatchEvent(Component.java:4698)
	at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1887)
	at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:762)
	at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1027)
	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:899)
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:727)
	at java.awt.Component.dispatchEventImpl(Component.java:4742)
	at java.awt.Container.dispatchEventImpl(Container.java:2287)
	at java.awt.Window.dispatchEventImpl(Window.java:2719)
	at java.awt.Component.dispatchEvent(Component.java:4698)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:747)
	at java.awt.EventQueue.access$300(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:706)
	at java.awt.EventQueue$3.run(EventQueue.java:704)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.awt.EventQueue$4.run(EventQueue.java:718)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:717)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

```

**Comment by ChristianGruen** [comment]
Thanks! Hm, sounds like a general Java issue. I will do some research on the error message. More feedback of any kind is welcome.

**Comment by ChristianGruen** [comment]
Did you already try Java 8?... http://bugs.java.com/bugdatabase/view_bug.do?bug_id=7107490

**Comment by ChristianGruen** [comment]
Has to do with Version <= 7 of Java... Closing this.
