### ISSUE TITLE
XQuery: Visitor cannot handle function items

### ISSUE THREAD

**Issue by ChristianGruen** [BaseXdb/basex#1308]
```xquery
declare variable $f := random-number-generator()?next;
$f
```

Stack trace:

```
java.lang.RuntimeException: Not Expected.
	at org.basex.util.Util.notExpected(Util.java:62)
	at org.basex.util.Util.notExpected(Util.java:52)
	at org.basex.query.func.fn.RuntimeExpr.accept(RuntimeExpr.java:90)
	at org.basex.query.value.item.FuncItem.visit(FuncItem.java:194)
	at org.basex.query.QueryCompiler$1.funcItem(QueryCompiler.java:90)
	at org.basex.query.value.item.FuncItem.accept(FuncItem.java:188)
	at org.basex.query.MainModule.visit(MainModule.java:152)
	at org.basex.query.QueryCompiler.usedDecls(QueryCompiler.java:62)
	at org.basex.query.QueryContext.plan(QueryContext.java:581)
	at org.basex.query.QueryProcessor.plan(QueryProcessor.java:335)
	at org.basex.core.cmd.AQuery.plan(AQuery.java:258)
	at org.basex.core.cmd.AQuery.query(AQuery.java:78)
	at org.basex.core.cmd.XQuery.run(XQuery.java:22)
	at org.basex.core.Command.run(Command.java:398)
	at org.basex.core.Command.execute(Command.java:100)
	at org.basex.gui.GUI.exec(GUI.java:478)
	at org.basex.gui.GUI.access$4(GUI.java:431)
	at org.basex.gui.GUI$7.run(GUI.java:420)
```

**Comment by ChristianGruen** [comment]
Hm, I wonder why this went through in the first run… @LeoWoerteler: any ideas? Is it the constant stack-frame size 1 that causes trouble?

```xquery
fn:random-number-generator()?permute(1 to 100)
```

```
Improper use? Potential bug? Your feedback is welcome:
Contact: basex-talk@mailman.uni-konstanz.de
Version: BaseX 8.5 beta
Java: Oracle Corporation, 1.8.0_91
OS: Windows 10, amd64
Stack Trace:
java.lang.RuntimeException: $seq_0 index: -1, slot: -1
        at org.basex.util.Util.notExpected(Util.java:62)
        at org.basex.query.var.QueryStack.pos(QueryStack.java:101)
        at org.basex.query.var.QueryStack.set(QueryStack.java:123)
        at org.basex.query.QueryContext.set(QueryContext.java:789)
        at org.basex.query.value.item.FuncItem.invValue(FuncItem.java:127)
        at org.basex.query.func.FuncCall.invoke(FuncCall.java:87)
        at org.basex.query.func.FuncCall.value(FuncCall.java:61)
        at org.basex.query.func.FuncCall.iter(FuncCall.java:66)
        at org.basex.query.MainModule.iter(MainModule.java:119)
```

**Comment by LeoWoerteler** [comment]
Oh, the `Var` is never assigned a stack slot! This [happens in the `VarScope`](https://github.com/BaseXdb/basex/blob/c56ac04/basex-core/src/main/java/org/basex/query/var/VarScope.java#L42).

**Comment by LeoWoerteler** [comment]
By the way, why is `fn:random-number-generator([seed])` declared as *non-deterministic*? It seems very deterministic to me.

**Comment by ChristianGruen** [comment]
> By the way, why is `fn:random-number-generator([seed])` declared as *non-deterministic*? It seems very deterministic to me.

True ;) And thanks for the swift fix.
