### ISSUE TITLE
XQuery, parallel execution

### ISSUE THREAD

**Issue by ChristianGruen** [BaseXdb/basex#1329]
Using xquery:fork-join, errors can happen. Examples:
- Static variable depends on itself: $C:VALUES
- Item expected, sequence found: (element erstellt {...}, ...).

Some more work is required to find out which operations are not completely thread-safe.

**XQuery** (with the `next` branch):

``` xquery
let $x := <x/>
return xquery:fork-join(
  for $i in 1 to 10000
  return function() { $x/text() }
)
```

**Result**:

```
[XPDY0002] text(): no context value bound.
```

**Comment by ChristianGruen** [comment]
Exception raised by GUI (if query with parallel threads is stopped):

```
Exception in thread "Thread-43" java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
        at java.util.ArrayList$Itr.next(Unknown Source)
        at org.basex.core.jobs.Job.state(Job.java:125)
        at org.basex.core.jobs.Job.state(Job.java:125)
        at org.basex.core.jobs.Job.state(Job.java:125)
        at org.basex.core.jobs.Job.state(Job.java:125)
        at org.basex.core.jobs.Job.state(Job.java:125)
        at org.basex.core.jobs.Job.state(Job.java:125)
        at org.basex.core.jobs.Job.state(Job.java:125)
        at org.basex.core.jobs.Job.state(Job.java:125)
        at org.basex.core.jobs.Job.state(Job.java:125)
        at org.basex.core.jobs.Job.state(Job.java:125)
        at org.basex.core.jobs.Job.state(Job.java:125)
        at org.basex.core.jobs.Job.state(Job.java:125)
        at org.basex.core.jobs.Job.state(Job.java:125)
        at org.basex.core.jobs.Job.state(Job.java:125)
        at org.basex.core.jobs.Job.state(Job.java:125)
        at org.basex.core.jobs.Job.state(Job.java:125)
        at org.basex.core.jobs.Job.stop(Job.java:96)
        at org.basex.gui.GUI.stop(GUI.java:569)
        at org.basex.gui.GUI.exec(GUI.java:561)
        at org.basex.gui.GUI.access$4(GUI.java:431)
        at org.basex.gui.GUI$7.run(GUI.java:420)
```

**Comment by ChristianGruen** [comment]
* [ ] Code to be checked: flagged with `[SINGLE]` in the `next` branch.
* [ ] Variable assignmnets (independent variable scope?).

**Comment by ChristianGruen** [comment]
Should be fixed

**Comment by ChristianGruen** [comment]
`Static variable depends on itself: $C:VALUES` error is not resolved yet.

**Comment by litlfred** [comment]
I am experiencing this issue intermittently.  Anything I can do to help resolve this?

**Comment by ChristianGruen** [comment]
Any example that is as concise as possible would be great.

**Comment by ChristianGruen** [comment]
Does the problem also occur with the [latest stable snapshot](http://files.basex.org/releases/latest/)?

**Comment by ChristianGruen** [comment]
Short version: `xquery:fork-join((1 to 1000) ! function() { <x/>[@a] })`
