### ISSUE TITLE
RESTXQ: Invalid HTTP status code in response

### ISSUE THREAD

**Issue by ChristianGruen** [BaseXdb/basex#1336]
An IllegalArgumentException will be raised by Jetty if a specified reponse status code is no valid integer:

```xquery
declare %rest:path("x") function local:x() {
  <rest:response>
    <http:response status="4x4"/>
  </rest:response>,
  <xml/>
};
```

```
java.lang.IllegalArgumentException
        at org.eclipse.jetty.server.Response.setStatus(Response.java:852)
        at org.basex.http.HTTPContext.status(HTTPContext.java:256)
        at org.basex.http.restxq.RestXqResponse.create(RestXqResponse.java:103)
        at org.basex.http.restxq.RestXqModule.process(RestXqModule.java:105)
        at org.basex.http.restxq.RestXqFunction.process(RestXqFunction.java:107)
        at org.basex.http.restxq.RestXqServlet.run(RestXqServlet.java:44)
```

**Comment by ChristianGruen** [comment]
The only clean solution seems to be the invocation of the deprecated [HTTPServletResponse.setStatus](https://tomcat.apache.org/tomcat-7.0-doc/servletapi/javax/servlet/http/HttpServletResponse.html#setStatus(int,%20java.lang.String)) function. There seems to be no other way to create both a status message (reason phrase) and a body.
