### ISSUE TITLE
SQL with BaseX 8.5.3

### ISSUE THREAD

**Issue by apb2006** [BaseXdb/basex#1341]
Using BaseX 8.5 with ojdbc6.jar  in lib
```
(: ojdbc6.jar  in lib :)
let $sql:="select ...with several joins"
let $_:=sql:init("oracle.jdbc.OracleDriver")
let $conn := sql:connect("jdbc:oracle:thin:..@//..")
return sql:execute($conn, $sql)
```
Works fine. But in 8.5.3
```
Error:
Improper use? Potential bug? Your feedback is welcome:
Contact: basex-talk@mailman.uni-konstanz.de
Version: BaseX 8.5.3
Java: Oracle Corporation, 1.8.0_92
OS: Windows 7, x86
Stack Trace: 
java.lang.RuntimeException: Class org.basex.query.QueryResources can not access a member of class org.basex.query.func.sql.JDBCConnections with modifiers ""
	at org.basex.util.Util.notExpected(Util.java:62)
	at org.basex.query.QueryResources.index(QueryResources.java:121)
	at org.basex.query.func.sql.SqlFn.jdbc(SqlFn.java:36)
	at org.basex.query.func.sql.SqlConnect.item(SqlConnect.java:35)
	at org.basex.query.expr.ParseExpr.value(ParseExpr.java:65)
	at org.basex.query.QueryContext.value(QueryContext.java:410)
	at org.basex.query.expr.gflwor.Let$LetEval.next(Let.java:183)
	at org.basex.query.expr.gflwor.GFLWOR$1.next(GFLWOR.java:95)
	at org.basex.query.MainModule$1.next(MainModule.java:121)
	at org.basex.query.QueryContext.cache(QueryContext.java:652)
	at org.basex.query.QueryProcessor.cache(QueryProcessor.java:114)
	at org.basex.core.cmd.AQuery.query(AQuery.java:88)
	at org.basex.core.cmd.XQuery.run(XQuery.java:22)
	at org.basex.core.Command.run(Command.java:253)
	at org.basex.core.Command.execute(Command.java:99)
	at org.basex.gui.GUI.exec(GUI.java:478)
	at org.basex.gui.GUI.access$400(GUI.java:43)
	at org.basex.gui.GUI$7.run(GUI.java:420)
```
Maybe related to https://www.mail-archive.com/basex-talk@mailman.uni-konstanz.de/msg08593.html

**Comment by ChristianGruen** [comment]
Resolved in the latest snapshot, thanks.
