### ISSUE TITLE
Possible concurrency issue: NullPointerException in DiskData.close()

### ISSUE THREAD

**Issue by dirkk** [BaseXdb/basex#1343]
As reported in https://mailman.uni-konstanz.de/pipermail/basex-talk/2016-August/011205.html:

> 
I had a first test environment, with only 4 isntances, and everything
was working perfectly.
Now, I'm working on target environment, a bigger computer with 8
instances. Process fails, at least one time per instance, so between 8
and 12 times on 100 process. The exception is 
```
java.lang.NullPointerException
        at org.basex.data.DiskData.write(DiskData.java:136)
        at org.basex.data.DiskData.close(DiskData.java:151)
        at org.basex.core.Datas.unpin(Datas.java:54)
        at org.basex.core.cmd.Close.close(Close.java:45)
        at org.basex.query.QueryResources.close(QueryResources.java:110)
        at org.basex.query.QueryContext.close(QueryContext.java:596)
        at org.basex.query.QueryProcessor.close(QueryProcessor.java:251)
        at org.basex.core.cmd.AQuery.query(AQuery.java:124)
        at org.basex.core.cmd.XQuery.run(XQuery.java:22)
        at org.basex.core.Command.run(Command.java:398)
        at org.basex.core.Command.execute(Command.java:100)
        at org.basex.server.ClientListener.run(ClientListener.java:136)
```

**Comment by ChristianGruen** [comment]
Closed for now (no further hints on how to reproduce it, and if it persists with the lates version).
