### ISSUE TITLE
Sybase JDBC driver

### ISSUE THREAD

**Issue by ChristianGruen** [BaseXdb/basex#1384]
* Following http://docs.basex.org/wiki/SQL_Module#Direct_queries
* JTDS driver: https://sourceforge.net/projects/jtds/files/jtds/1.3.1/

Error:

```
Error 500 Unexpected error: Improper use? Potential bug? Your feedback is welcome:
Version: BaseX 8.5.3
Java: Oracle Corporation, 1.8.0_111
OS: Linux
amd64 java.lang.RuntimeException: Class org.basex.query.QueryResources can not access a 
    member of class org.basex.query.func.sql.JDBCConnections with modifiers ""
at org.basex.util.Util.notExpected(Util.java:62)
at org.basex.query.QueryResources.index(QueryResources.java:121)
at org.basex.query.func.sql.SqlFn.jdbc(SqlFn.java:36)
at org.basex.query.func.sql.SqlConnect.item(SqlConnect.java:35)
...
```

**Comment by ChristianGruen** [comment]
Fixed with latest version (same issue as with other SQL drivers discussed before).
