### ISSUE TITLE
Query Stack, RuntimeException ($key_9 index: 1, slot: 1)

### ISSUE THREAD

**Issue by ChristianGruen** [BaseXdb/basex#1424]
**XQuery:**

```xquery
(: works if function is not inlined ... %basex:inline(0) :)
declare function local:f() {
  let $func := function($key) { map { $key: 'ok' }($key) }
  let $input := <ok/>
  (: works if next 'let' is changed to 'for' (no 'inlining $call_3' optimization) :)
  let $call := $func(name($input))
  return function() { $call }
};
local:f()
```

**Output:**

```
Stack Trace: 
java.lang.RuntimeException: $key_9 index: 1, slot: 1
	at org.basex.util.Util.notExpected(Util.java:62)
	at org.basex.query.var.QueryStack.pos(QueryStack.java:101)
	at org.basex.query.var.QueryStack.set(QueryStack.java:123)
	at org.basex.query.QueryContext.set(QueryContext.java:756)
	at org.basex.query.expr.gflwor.Let$LetEval.next(Let.java:184)
	at org.basex.query.expr.gflwor.GFLWOR.value(GFLWOR.java:71)
	at org.basex.query.func.Closure.item(Closure.java:288)
	at org.basex.query.func.Closure.value(Closure.java:321)
	at org.basex.query.func.Closure.iter(Closure.java:326)
	at org.basex.query.func.Closure.iter(Closure.java:34)
	at org.basex.query.expr.gflwor.GFLWOR$1.next(GFLWOR.java:99)
	at org.basex.query.scope.MainModule$1.next(MainModule.java:121)
	at org.basex.query.QueryContext.cache(QueryContext.java:635)
	at org.basex.query.QueryProcessor.cache(QueryProcessor.java:113)
```

**Comment by LeoWoerteler** [comment]
When copying a `Closure`, the expressions that compute the values in the closure (in `Closure#global`, strange naming) are copied in the wrong, inner scope. This seems to have been introduced in 77248c8, which has made choosing the correct scope more tricky.

This is how `local:f()` looks before inlining, where `$..._o` and `$..._i` mark variables in the scope of `local:f` and the *inline closure*, respectively:
```xquery
declare function local:f() {
  let $input_o := <ok/>
  return (
    (: inline-closure :)
    let $call_i :=
        let $key_o := name($input_o)
        return map { $key_o:"ok" }($key_o)
    return function() { $call_i }
  )
};
```
The innermost *FLWOR* expression (binding `$key_o`) is copied into the `_i` scope, but evaluated inside the `_o` scope, leading to an out-of-stack access.

I will open a pull request with a fix and a regression test later today.

**Comment by ChristianGruen** [comment]
Thanks so much for taking your time.
