### ISSUE TITLE
java.lang.NullPointerException on equality test?

### ISSUE THREAD

**Issue by apb2006** [BaseXdb/basex#1427]
Running `test.xq` in the GUI I am getting a NullPointerException. Happening with 8.6.1 and latest beta.
```
(: java.lang.NullPointerException :)
import module namespace entity = 'quodatum.models.generated' at 'models2.xqm';

declare function local:get($entity as map(*),$name as xs:string)
as element(*){
    let $results:=$entity("data")()
    return $results[$name=$entity?access?name(.)]
};
let $name:=string(db:list()[1])
 let $entity:=$entity:list("database")
  (: let $results:=$entity("data")()
  let $result:= $results[$name=$entity?access?name(.)] :)
  let $result:=local:get($entity,$name)
 return $result
```
It does not happen if I remove the string call from `let $name:=string(db:list()[1])` or use the commented out code in place of `local:get()`

PS Seems GUI 8.6.2 is not showing a full stack trace?

Improper use? Potential bug? Your feedback is welcome:
Contact: basex-talk@mailman.uni-konstanz.de
Version: BaseX 8.6.2 beta 9442d19
Java: Oracle Corporation, 1.8.0_121
OS: Windows 10, amd64
Stack Trace: 
java.lang.NullPointerException

[issue.zip](https://github.com/BaseXdb/basex/files/803900/issue.zip)

**Comment by apb2006** [comment]
>Seems GUI 8.6.2 is not showing a full stack trace?
Mmm, it does for the first 5 executions after that only 1st line shown . Strange! Ok in 8.6.1
Error:
Improper use? Potential bug? Your feedback is welcome:
Contact: basex-talk@mailman.uni-konstanz.de
Version: BaseX 8.6.2 beta 9442d19
Java: Oracle Corporation, 1.8.0_121
OS: Windows 10, amd64
Stack Trace: 
java.lang.NullPointerException
	at org.basex.query.value.item.QNm.eq(QNm.java:244)
	at org.basex.query.expr.path.Test.sameAs(Test.java:72)
	at org.basex.query.value.type.SeqType.intersect(SeqType.java:556)
	at org.basex.query.value.type.SeqType.promotable(SeqType.java:514)
	at org.basex.query.var.Var.refineType(Var.java:131)
	at org.basex.query.expr.gflwor.Let.optimize(Let.java:100)
	at org.basex.query.expr.gflwor.Let.optimize(Let.java:29)
	at org.basex.query.expr.gflwor.ForLet.compile(ForLet.java:42)
	at org.basex.query.expr.gflwor.Let.compile(Let.java:84)
	at org.basex.query.expr.gflwor.ForLet.inline(ForLet.java:68)
	at org.basex.query.expr.gflwor.GFLWOR.inline(GFLWOR.java:698)
	at org.basex.query.expr.gflwor.GFLWOR.inlineLets(GFLWOR.java:365)
	at org.basex.query.expr.gflwor.GFLWOR.optimize(GFLWOR.java:146)
	at org.basex.query.expr.gflwor.GFLWOR.compile(GFLWOR.java:121)
	at org.basex.query.scope.MainModule.comp(MainModule.java:82)
	at org.basex.query.QueryCompiler.compile(QueryCompiler.java:114)
	at org.basex.query.QueryCompiler.compile(QueryCompiler.java:105)
	at org.basex.query.QueryContext.compile(QueryContext.java:306)
	at org.basex.query.QueryProcessor.compile(QueryProcessor.java:79)
	at org.basex.core.cmd.AQuery.query(AQuery.java:78)
	at org.basex.core.cmd.XQuery.run(XQuery.java:22)
	at org.basex.core.Command.run(Command.java:257)
	at org.basex.core.Command.execute(Command.java:93)
	at org.basex.gui.GUI.exec(GUI.java:471)
	at org.basex.gui.GUI.access$300(GUI.java:44)
	at org.basex.gui.GUI$6.run(GUI.java:413)

**Comment by ChristianGruen** [comment]
**Minimized query:**

```
let $a := function($f) as element(*) { $f() }
let $b := $a(function() as element(xml)* { <xml/> })
return $b
```

**Comment by ChristianGruen** [comment]
Thanks for reporting.
