### ISSUE TITLE
Unexpected Exception reading db from fork-join

### ISSUE THREAD

**Issue by jdoe-id1** [BaseXdb/basex#1443]
I use a xquery to test a soap service. Sometime (~ 1:100.000) when I call "fork-calls(50)" the following exception will thrown:
```java
java.io.IOException: Stream Closed
	at java.io.RandomAccessFile.seek0(Native Method)
	at java.io.RandomAccessFile.seek(RandomAccessFile.java:557)
	at org.basex.io.random.TableDiskAccess.read(TableDiskAccess.java:518)
	at org.basex.io.random.TableDiskAccess.readPage(TableDiskAccess.java:483)
	at org.basex.io.random.TableDiskAccess.cursor(TableDiskAccess.java:462)
	at org.basex.io.random.TableDiskAccess.read1(TableDiskAccess.java:148)
	at org.basex.data.Data.kind(Data.java:293)
	at org.basex.query.value.node.DBNode$4.next(DBNode.java:337)
	at org.basex.query.value.node.DBNode$4.next(DBNode.java:328)
	at org.basex.query.iter.BasicNodeIter$2.hasNext(BasicNodeIter.java:38)
	at org.basex.query.expr.path.IterPosStep$1.next(IterPosStep.java:64)
	at org.basex.query.expr.path.IterPosStep$1.next(IterPosStep.java:34)
	at org.basex.query.expr.path.IterPath$1.next(IterPath.java:50)
	at org.basex.query.expr.path.IterPath$1.next(IterPath.java:34)
	at org.basex.query.iter.Iter.value(Iter.java:51)
	at org.basex.query.expr.ParseExpr.value(ParseExpr.java:68)
	at org.basex.query.QueryContext.value(QueryContext.java:405)
	at org.basex.query.expr.gflwor.Let$LetEval.next(Let.java:182)
	at org.basex.query.expr.gflwor.GFLWOR.value(GFLWOR.java:71)
	at org.basex.query.QueryContext.value(QueryContext.java:405)
	at org.basex.query.func.StaticFunc.invValue(StaticFunc.java:182)
	at org.basex.query.func.FuncCall.invoke(FuncCall.java:87)
	at org.basex.query.func.FuncCall.value(FuncCall.java:60)
	at org.basex.query.QueryContext.value(QueryContext.java:405)
	at org.basex.query.expr.gflwor.Let$LetEval.next(Let.java:182)
	at org.basex.query.expr.gflwor.GFLWOR.item(GFLWOR.java:58)
	at org.basex.query.expr.ParseExpr.toEmptyNode(ParseExpr.java:414)
	at org.basex.query.func.http.HttpSendRequest.iter(HttpSendRequest.java:23)
	at org.basex.query.QueryContext.iter(QueryContext.java:394)
	at org.basex.query.expr.constr.Constr.add(Constr.java:69)
	at org.basex.query.expr.constr.CElem.item(CElem.java:94)
	at org.basex.query.expr.constr.CElem.item(CElem.java:23)
	at org.basex.query.expr.ParseExpr.value(ParseExpr.java:65)
	at org.basex.query.QueryContext.value(QueryContext.java:405)
	at org.basex.query.value.item.FuncItem.invValue(FuncItem.java:117)
	at org.basex.query.func.FuncCall.invoke(FuncCall.java:87)
	at org.basex.query.func.FuncCall.value(FuncCall.java:159)
	at org.basex.query.value.item.FItem.invokeValue(FItem.java:44)
	at org.basex.query.func.xquery.XQueryTask.compute(XQueryTask.java:61)
	at org.basex.query.func.xquery.XQueryTask.compute(XQueryTask.java:15)
	at java.util.concurrent.RecursiveTask.exec(RecursiveTask.java:94)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:401)
	at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:734)
	at org.basex.query.func.xquery.XQueryTask.compute(XQueryTask.java:74)
	at org.basex.query.func.xquery.XQueryTask.compute(XQueryTask.java:15)
	at java.util.concurrent.RecursiveTask.exec(RecursiveTask.java:94)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.execLocalTasks(ForkJoinPool.java:1040)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1058)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```
XQuery (module):

```xquery
module namespace m="http://afoundation.idgroup.aero/xq/object-service/sim/soap";

declare namespace se="http://jojo";

declare function m:change-namespace-deep($in as node()*, $new-namespace as xs:string, $prefix as xs:string ) 
as node()* {
  for $node in $in
  return 
    if ($node instance of element()) then 
      element { QName ($new-namespace, concat($prefix, if ($prefix = '') then '' else ':',  local-name($node))) } {
        $node/@*, 
        m:change-namespace-deep($node/node(), $new-namespace, $prefix)
      }
    else if ($node instance of document-node()) then
      (: step through document nodes :)
      m:change-namespace-deep($node/node(), $new-namespace, $prefix)
      (: for comments and PIs :)
    else 
      $node
};

declare function m:transform-request($item as item()*)
{
  element flightLegRequest {
    element key {
      element flightIdDate { $item/key/flightIdDate/text() }, 
      element airline      { $item/key/airline/text() }, 
      element flightNumber { $item/key/flightNr/text() }, 
      if ($item/key/suffix/text()) then 
        element operationalSuffix {$item/key/suffix/text() } 
          else (), 
          element departureAirport { $item/key/dep/text() }, 
          element arrivalAirport   { $item/key/arv/text() }, 
          if ($item/key/duplicate/text()) then 
            element duplicateSequenceNumber { $item/key/duplicate/text() } 
          else ()  
      }
  }
};
 
declare function m:create-request() {
   let $url       := "...some..."
   let $fl        := collection("lala/lol.xml")/flightLeg
   let $leg       := xs:integer(random:integer(1000)+1)
   let $flightLeg := $fl/flightLeg[$leg]
   let $flightLegReq := m:transform-request($flightLeg)
   let $request :=
   <http:request href="{$url}" method='post' timeout="10">
     <http:header name="Content-Type" value="text/xml;charset=UTF-8"/>
     <http:body media-type='application/xml'>
       <SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:se="http://jojo">
         <SOAP-ENV:Header/>
         <SOAP-ENV:Body>
           { m:change-namespace-deep($flightLegReq, "http://jojo", 'se')  }           
         </SOAP-ENV:Body>
       </SOAP-ENV:Envelope>
     </http:body>
   </http:request>
   
   return $request
};

declare function m:fork-calls($num as xs:integer) 
{
  let $funcs := 
    for $n in 1 to $num
    return 
      function() { 
        element resp { 
          m:create-request()
          => http:send-request() 
       }
    }
      
  return
     xquery:fork-join($funcs)
};
```

**Comment by ChristianGruen** [comment]
Maybe this is related to https://github.com/BaseXdb/basex/issues/1329. In order to fix this, we’ll probably need some data for testing. Do you think there’s any chance for you to provide a self-contained example?

**Comment by ChristianGruen** [comment]
Closing this for now (#1329 is still open).
