### ISSUE TITLE
WebDAV PROPFIND throws on on resources with spaces in their name

### ISSUE THREAD

**Issue by devatwork** [BaseXdb/basex#1473]
The BaseX WebDAV implementation errors internally when a PROPFIND is requested on a resource with a space in the name.

Steps to repro:

1. Create a db `test`.
1. Create a file `with spaces.xml`.
1. Run `curl --basic --user 'user:pass' --request PROPFIND --header "Content-Type: text/xml" http://localhost:8984/webdav/test/with%20spaces.xml --data-binary "<?xml version=\"1.0\" encoding=\"utf-8\" ?><D:propfind xmlns:D=\"DAV:\"><allprop/></D:propfind>"` where you replace `user:pass` with the appropriate credentials.

This will result in the following stack trace:

```
[qtp32829455-18] INFO com.bradmcevoy.http.webdav.WebDavProtocol - resourceTypeHelper: class com.bradmcevoy.http.webdav.WebDavResourceTypeHelper
[qtp32829455-18] INFO com.bradmcevoy.http.webdav.WebDavProtocol - quotaDataAccessor: class com.bradmcevoy.http.quota.DefaultQuotaDataAccessor
[qtp32829455-18] INFO com.bradmcevoy.http.webdav.WebDavProtocol - creating default patcheSetter: class com.bradmcevoy.http.webdav.PropertySourcePatchSetter
[qtp32829455-18] INFO com.bradmcevoy.http.HttpManager - PROPFIND :: http://localhost:8984/webdav/test/with spaces.xml - http://localhost:8984/webdav/test/with spaces.xml
[qtp32829455-18] ERROR com.bradmcevoy.http.webdav.PropFindHandler - Exception parsing url. request class: class org.basex.http.webdav.WebDAVRequest. Please check the client application is usign percentage encoding (see http://en.wikipedia.org/wiki/Percent-encoding)
[qtp32829455-18] ERROR com.bradmcevoy.http.StandardFilter - process
java.lang.RuntimeException: Exception parsing url, indicating the requested URL is not correctly encoded. Please check the client application. Requested url is: http://localhost:89
        at xml.bradmcevoy.http.webdav.PropFindHandler.processExistingResource(PropFindHandler.java:135)
        at com.bradmcevoy.http.ResourceHandlerHelper.processResource(ResourceHandlerHelper.java:149)
        at com.bradmcevoy.http.webdav.PropFindHandler.processResource(PropFindHandler.java:103)
        at com.bradmcevoy.http.ResourceHandlerHelper.process(ResourceHandlerHelper.java:91)
        at com.bradmcevoy.http.webdav.PropFindHandler.process(PropFindHandler.java:97)
        at com.bradmcevoy.http.StandardFilter.process(StandardFilter.java:52)
        at com.bradmcevoy.http.FilterChain.process(FilterChain.java:40)
        at com.bradmcevoy.http.HttpManager.process(HttpManager.java:228)
        at org.basex.http.webdav.WebDAVServlet.run(WebDAVServlet.java:34)
        at org.basex.http.BaseXServlet.service(BaseXServlet.java:59)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:684)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:503)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:429)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
        at org.eclipse.jetty.server.Server.handle(Server.java:370)
        at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)
        at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:982)
        at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1043)
        at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:861)
        at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:236)
        at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:696)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:53)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.net.URISyntaxException: Illegal character in path at index 38: http://localhost:8984/webdav/test/with spaces.xml
        at java.net.URI$Parser.fail(Unknown Source)
        at java.net.URI$Parser.checkChars(Unknown Source)
        at java.net.URI$Parser.parseHierarchical(Unknown Source)
        at java.net.URI$Parser.parse(Unknown Source)
        at java.net.URI.<init>(Unknown Source)
        at com.bradmcevoy.http.webdav.PropFindPropertyBuilder.appendResponses(PropFindPropertyBuilder.java:104)
        at com.bradmcevoy.http.webdav.PropFindPropertyBuilder.buildProperties(PropFindPropertyBuilder.java:86)
        at com.bradmcevoy.http.webdav.PropFindHandler.processExistingResource(PropFindHandler.java:132)
        ... 33 more
```

As far as I can see the request is correctly encoded. The same behavior can be observed using other WebDAV clients like WinSCP for example. I've tested this with other WebDAV servers and they seem to be able to handle the encoded resource name properly which leads me to believe that this may be an issue in BaseX or the underlying milton lib.

Is this considered a bug? Let me know if I can be of any further assistance diagnosing this issue.

**Comment by ChristianGruen** [comment]
Thanks for the observation. I will check if this is something that can be fixed by us, or would need to be handled by the developer of the WebDAV library.

**Comment by ChristianGruen** [comment]
Seems as if this is something that needs to be fixed outside BaseX (so I’ll be closing this issue). It was already reported on the Milton WebDAV mailing list (http://lists.justthe.net/pipermail/milton-users/2011-August/003244.html), but it has probably not been fixed yet.

As far as I know, Brad McEvoy has stopped the development of his free WebDAV version (see http://milton.io for more details), but maybe it helps to get into contact with him?

**Comment by TomGroeneboer** [comment]
I am experiencing the same issued. It seems that you are still using version 1.8.1.4 of Milton. However, version 2.7.3.0 is released a few days ago. I can imagine that the most recent version has some bugfixes which might include this one.
