### ISSUE TITLE
Empty following axis causes RuntimeException

### ISSUE THREAD

**Issue by AndrewSales** [BaseXdb/basex#1478]
Thank you for 8.6.5!

The following script:
`<commands>
  <create-db name='test'/>
  <add path='a.xml'><a/></add>
  <add path='b.xml'><a/></add>
  <xquery>//a/following::*</xquery>
</commands>`

results in:

Improper use? Potential bug? Your feedback is welcome:
Contact: basex-talk@mailman.uni-konstanz.de
Version: BaseX 8.6.5
Java: Oracle Corporation, 1.8.0_144
OS: Windows 7, amd64
Stack Trace: 
java.lang.RuntimeException: Data Access out of bounds:
- pre value: 4
- table size: 4
- first/next pre value: 0/4
- #total/used pages: 1/1
- accessed page: 0 (1 > 0]
	at org.basex.util.Util.notExpected(Util.java:62)
	at org.basex.io.random.TableDiskAccess.cursor(TableDiskAccess.java:455)
	at org.basex.io.random.TableDiskAccess.read1(TableDiskAccess.java:148)
	at org.basex.data.Data.kind(Data.java:293)
	at org.basex.query.value.node.DBNode$7.next(DBNode.java:397)
	at org.basex.query.value.node.DBNode$7.next(DBNode.java:1)
	at org.basex.query.iter.BasicNodeIter$2.hasNext(BasicNodeIter.java:39)
	at org.basex.query.expr.path.IterStep$1.next(IterStep.java:38)
	at org.basex.query.expr.path.IterStep$1.next(IterStep.java:1)
	at org.basex.query.expr.path.IterPath$1.next(IterPath.java:50)
	at org.basex.query.expr.path.IterPath$1.next(IterPath.java:1)
	at org.basex.query.scope.MainModule$1.next(MainModule.java:125)
	at org.basex.core.cmd.AQuery.query(AQuery.java:94)
	at org.basex.core.cmd.XQuery.run(XQuery.java:22)
	at org.basex.core.Command.run(Command.java:257)
	at org.basex.core.cmd.Execute.run(Execute.java:58)
	at org.basex.core.Command.run(Command.java:257)
	at org.basex.core.Command.execute(Command.java:93)
	at org.basex.gui.GUI.exec(GUI.java:474)
	at org.basex.gui.GUI.access$4(GUI.java:428)
	at org.basex.gui.GUI$6.run(GUI.java:416)

It occurs under 8.6.4 also, but I only just noticed. Is this related to #1374?

**Comment by ChristianGruen** [comment]
Indeed this closely resembled the bug you reported in #1374… It has finally been fixed (as I hope). Thanks.
