### ISSUE TITLE
macOS GUI: Keyboard shortcuts

### ISSUE THREAD

**Issue by holu** [BaseXdb/basex#1590]
Shortcuts in 'View' (such as, CMD+R, CMD+I, CMD+E) are working as expected.
Shortcuts in 'Database' (CMD+N, CMD+M) and 'Editor' (such as CMD+T, CMD+W) are defunct.

Relates #1582

**Comment by ChristianGruen** [comment]
For some enigmatic reason, the action listener will be called twice for toggleable menu items. One event is fired by the menu item itself, but only the following one would actually be required:

```
    at org.basex.gui.GUIMenuCmd$38.execute(GUIMenuCmd.java:597)
    at org.basex.gui.GUIMenu.lambda$0(GUIMenu.java:77)
    at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
    at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
    at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
    at javax.swing.JToggleButton$ToggleButtonModel.setPressed(JToggleButton.java:308)
    at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
    at javax.swing.AbstractButton.doClick(AbstractButton.java:356)
    at javax.swing.plaf.basic.BasicMenuItemUI$Actions.actionPerformed(BasicMenuItemUI.java:811)
    at javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1663)
    at javax.swing.JComponent.processKeyBinding(JComponent.java:2882)
    at javax.swing.JMenuBar.processBindingForKeyStrokeRecursive(JMenuBar.java:699)
    at javax.swing.JMenuBar.processBindingForKeyStrokeRecursive(JMenuBar.java:706)
    at javax.swing.JMenuBar.processBindingForKeyStrokeRecursive(JMenuBar.java:706)
    at javax.swing.JMenuBar.processKeyBinding(JMenuBar.java:677)
    at javax.swing.KeyboardManager.fireBinding(KeyboardManager.java:307)
    at javax.swing.KeyboardManager.fireKeyboardAction(KeyboardManager.java:293)
    at javax.swing.JComponent.processKeyBindingsForAllComponents(JComponent.java:2974)
```

Ways to tackle this:
1. Reproduce the problem with a stripped down GUI instance. If the problem persists, try to find out if the issue has been reported by somewhere else.
2. Check out if cbd32289436f95c1afa4f06687d2cac419ca0a3b circumvents the problem (by replacing toggeable items with standard items).
