### ISSUE TITLE
jobs:list-details: Concurrent Modification Exception

### ISSUE THREAD

**Issue by ChristianGruen** [BaseXdb/basex#1603]
The error occurs if the registered jobs are listed, and if a job is removed during this process.

Stack Trace:

```
java.util.ConcurrentModificationException
 at java.util.LinkedList$ListItr.checkForComodification(LinkedList.java:966)
 at java.util.LinkedList$ListItr.next(LinkedList.java:888)
 at org.basex.query.expr.gflwor.GFLWOR.accept(GFLWOR.java:802)
 at org.basex.query.func.StaticFunc.visit(StaticFunc.java:266)
 at org.basex.query.QueryInfo$1.staticFuncCall(QueryInfo.java:173)
 at org.basex.query.func.StaticFuncCall.accept(StaticFuncCall.java:136)
 at org.basex.query.expr.Expr.visitAll(Expr.java:403)
 at org.basex.query.expr.SimpleMap.accept(SimpleMap.java:165)
 at org.basex.query.expr.Filter.accept(Filter.java:254)
 at org.basex.query.expr.gflwor.Let.accept(Let.java:112)
 at org.basex.query.expr.gflwor.GFLWOR.accept(GFLWOR.java:802)
 at org.basex.query.func.StaticFunc.visit(StaticFunc.java:266)
 at org.basex.query.QueryInfo$1.staticFuncCall(QueryInfo.java:173)
 at org.basex.query.func.StaticFuncCall.accept(StaticFuncCall.java:136)
 at org.basex.query.expr.Expr.visitAll(Expr.java:403)
 at org.basex.query.expr.Arr.accept(Arr.java:114)
 at org.basex.query.func.StaticFuncCall.accept(StaticFuncCall.java:136)
 at org.basex.query.expr.gflwor.Let.accept(Let.java:112)
 at org.basex.query.expr.gflwor.GFLWOR.accept(GFLWOR.java:802)
 at org.basex.query.func.StaticFunc.visit(StaticFunc.java:266)
 at org.basex.query.QueryInfo$1.staticFuncCall(QueryInfo.java:173)
 at org.basex.query.func.StaticFuncCall.accept(StaticFuncCall.java:136)
 at org.basex.query.expr.gflwor.Let.accept(Let.java:112)
 at org.basex.query.expr.gflwor.GFLWOR.accept(GFLWOR.java:802)
 at org.basex.query.func.StaticFunc.visit(StaticFunc.java:266)
 at org.basex.query.QueryInfo$1.staticFuncCall(QueryInfo.java:173)
 at org.basex.query.func.StaticFuncCall.accept(StaticFuncCall.java:136)
 at org.basex.query.scope.MainModule.visit(MainModule.java:153) ...
```

**Comment by ChristianGruen** [comment]
Interestingly, this error occurs only when listing jobs in the DBA (but the »concurrent modification« does not relate to the internal job lists, but rather to the GFLWOR clauses.

**Comment by ChristianGruen** [comment]
One more (which actually contains a JobListDetails reference this time):

```
java.util.ConcurrentModificationException
  at java.util.LinkedList$ListItr.checkForComodification(LinkedList.java:966)
  at java.util.LinkedList$ListItr.next(LinkedList.java:888)
  at org.basex.query.expr.gflwor.GFLWOR.toString(GFLWOR.java:855)
  at org.basex.util.TokenBuilder.token(TokenBuilder.java:378)
  at org.basex.util.TokenBuilder.addExt(TokenBuilder.java:337)
  at org.basex.query.func.StaticFunc.toString(StaticFunc.java:324)
  at java.lang.String.valueOf(String.java:2994)
  at java.lang.StringBuilder.append(StringBuilder.java:131)
  at org.basex.query.QueryInfo$1.staticFuncCall(QueryInfo.java:174)
  at org.basex.query.func.StaticFuncCall.accept(StaticFuncCall.java:136)
  at org.basex.query.expr.gflwor.Let.accept(Let.java:112)
  at org.basex.query.expr.gflwor.GFLWOR.accept(GFLWOR.java:802)
  at org.basex.query.func.StaticFunc.visit(StaticFunc.java:266)
  at org.basex.query.QueryInfo$1.staticFuncCall(QueryInfo.java:173)
  at org.basex.query.func.StaticFuncCall.accept(StaticFuncCall.java:136)
  at org.basex.query.scope.MainModule.visit(MainModule.java:153)
  at org.basex.query.QueryInfo.usedDecls(QueryInfo.java:159)
  at org.basex.query.QueryContext.toString(QueryContext.java:790)
  at org.basex.core.jobs.JobContext.toString(JobContext.java:83)
  at org.basex.core.cmd.JobsList.entry(JobsList.java:103)
  at org.basex.query.func.jobs.JobsListDetails.value(JobsListDetails.java:36)
  at org.basex.query.func.jobs.JobsListDetails.iter(JobsListDetails.java:53)
```

**Comment by ChristianGruen** [comment]
Fixed with https://github.com/BaseXdb/basex/issues/1607
