### ISSUE TITLE
BaseX GUI OutOfMemoryError GC overhead limit exceeded

### ISSUE THREAD

**Issue by aviationfan** [BaseXdb/basex#1677]
I ran the BaseX GUI this morning on my mac and before I did anything at all it ran out of memory. I then bumped up the max heap from 2G to 4G and it did it again.
Some Environment Details:
```
macOS 10.13.6 High Sierra
java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)
BaseX 9.2
```

Error output in the terminal
```
java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at javax.swing.SwingWorker.get(SwingWorker.java:602)
	at org.basex.gui.layout.GUIWorker$1.done(GUIWorker.java:40)
	at javax.swing.SwingWorker$5.run(SwingWorker.java:737)
	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(SwingWorker.java:832)
	at sun.swing.AccumulativeRunnable.run(AccumulativeRunnable.java:112)
	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(SwingWorker.java:842)
	at javax.swing.Timer.fireActionPerformed(Timer.java:313)
	at javax.swing.Timer$DoPostEvent.run(Timer.java:245)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
	at org.basex.util.Token.string(Token.java:113)
	at org.basex.util.TokenBuilder.toString(TokenBuilder.java:405)
	at org.basex.io.IOFile.add(IOFile.java:528)
	at org.basex.io.IOFile.create(IOFile.java:500)
	at org.basex.io.IOFile.<init>(IOFile.java:74)
	at org.basex.io.IOFile.<init>(IOFile.java:47)
	at org.basex.io.IOFile.children(IOFile.java:226)
	at org.basex.io.IOFile.children(IOFile.java:193)
	at org.basex.gui.view.project.ProjectFiles.add(ProjectFiles.java:167)
	at org.basex.gui.view.project.ProjectFiles.add(ProjectFiles.java:173)
	at org.basex.gui.view.project.ProjectFiles.add(ProjectFiles.java:173)
	at org.basex.gui.view.project.ProjectFiles.add(ProjectFiles.java:173)
	at org.basex.gui.view.project.ProjectFiles.add(ProjectFiles.java:173)
	at org.basex.gui.view.project.ProjectFiles.add(ProjectFiles.java:173)
	at org.basex.gui.view.project.ProjectFiles.add(ProjectFiles.java:173)
	at org.basex.gui.view.project.ProjectFiles.add(ProjectFiles.java:173)
	at org.basex.gui.view.project.ProjectFiles.add(ProjectFiles.java:173)
	at org.basex.gui.view.project.ProjectFiles.add(ProjectFiles.java:173)
	at org.basex.gui.view.project.ProjectFiles.add(ProjectFiles.java:173)
	at org.basex.gui.view.project.ProjectFiles.add(ProjectFiles.java:173)
	at org.basex.gui.view.project.ProjectFiles.add(ProjectFiles.java:173)
	at org.basex.gui.view.project.ProjectFiles.add(ProjectFiles.java:173)
	at org.basex.gui.view.project.ProjectFiles.add(ProjectFiles.java:173)
	at org.basex.gui.view.project.ProjectFiles.add(ProjectFiles.java:173)
	at org.basex.gui.view.project.ProjectFiles.add(ProjectFiles.java:173)
	at org.basex.gui.view.project.ProjectFiles.add(ProjectFiles.java:173)
	at org.basex.gui.view.project.ProjectFiles.add(ProjectFiles.java:173)
	at org.basex.gui.view.project.ProjectFiles.add(ProjectFiles.java:173)
	at org.basex.gui.view.project.ProjectFiles.add(ProjectFiles.java:173)
	at org.basex.gui.view.project.ProjectFiles.add(ProjectFiles.java:173)
	at org.basex.gui.view.project.ProjectFiles.add(ProjectFiles.java:173)
	at org.basex.gui.view.project.ProjectFiles.add(ProjectFiles.java:173)
```

Attaching a screen shot of VisualVM monitoring as well
![Basex_gui_fail_4_16_2019_8_52_AM](https://user-images.githubusercontent.com/955527/56221253-2a3ad300-6027-11e9-8170-15f429d25349.png)

I am wondering if this has something to do with Java on the Mac and the use of 1.8.

**Comment by aviationfan** [comment]
The behavior I observed happened by just opening the GUI and watching without executing any commands at all. No db create or open, nothing.

**Comment by ChristianGruen** [comment]
There seem to loops in your file system, caused by symbolic links. Does the problem persist if you change the project directory (either via the GUI, if possible, or in the .basexgui configuration file)?

**Comment by aviationfan** [comment]
That seemed to work
Changed this value
`PROJECTPATH = /Volumes/Big3_2/basex92/`

in the file 
`.basexgui`
And the gui seems to work fine. Must be a problem created by having multiple version of basex in different directories, something want to fix in the future.

**Comment by ChristianGruen** [comment]
Thanks. I remember this has been reported in the past. I’ll keep this open, and we’ll see if we can skip the traversal of symbolic links that have already been scanned.

**Comment by ChristianGruen** [comment]
A [new stable snapshot](http://files.basex.org/releases/latest/) is available. Could you please check it out and close the issue if the problem has been resolved?

**Comment by aviationfan** [comment]
Confirmed that it behaves normally with version 9.2.1
