### ISSUE TITLE
BaseX 9.2.4 - Resource not found

### ISSUE THREAD

**Issue by TheAifam5** [BaseXdb/basex#1706]
Hey!

I'm using BaseX (the latest version) in docker. I'm playing around for now, and when I tried to make a migration on the 9.2.4 version, the error occurs. I spent some time trying also to set the DBPATH through the JVM_BASEX environment but that does not help.
Then I downgraded to 8.5.3, and the issue is not present on that version.

Reproduce:
- Run basex in docker
- Log in into TTY
- Make a script like: `echo "CREATE DB test;"`
- Execute `/usr/local/bin/basexserver -d -c"$(cat /that_script_above.sh)"`

Logs:
```
bash-4.4# /dump/migration.sh 
/root/basex/.basex: writing new configuration file.
BaseX 9.2.4 beta [Server]
Server was started (port: 1984).
org.basex.core.BaseXException: Resource "/srv/;" not found.
        at org.basex.core.Command.execute(Command.java:94)
        at org.basex.api.client.LocalSession.execute(LocalSession.java:132)
        at org.basex.api.client.Session.execute(Session.java:36)
        at org.basex.core.CLI.execute(CLI.java:92)
        at org.basex.core.CLI.execute(CLI.java:76)
        at org.basex.core.CLI.execute(CLI.java:63)
        at org.basex.BaseXServer.<init>(BaseXServer.java:129)
        at org.basex.BaseXServer.<init>(BaseXServer.java:63)
        at org.basex.BaseXServer.main(BaseXServer.java:50)
Resource "/srv/;" not found.
Server was stopped (port: 1984).
java.net.SocketException: Socket closed
        at java.net.PlainSocketImpl.socketAccept(Native Method)
        at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:409)
        at java.net.ServerSocket.implAccept(ServerSocket.java:545)
        at java.net.ServerSocket.accept(ServerSocket.java:513)
        at org.basex.BaseXServer.run(BaseXServer.java:138)
        at java.lang.Thread.run(Thread.java:748)
```

PS. Looks like the directory structure has been changed. In older version is BaseXWeb, BaseXData etc....

**Comment by ChristianGruen** [comment]
> PS. Looks like the directory structure has been changed. In older version is BaseXWeb, BaseXData etc....

Exactly. You could try to follow the steps of our [documentation](http://docs.basex.org/wiki/Docker). If that doesn’t help, I invite you to send this to our mailing-list. Thanks!

**Comment by TheAifam5** [comment]
That does not help at all. I managed to get it working on a `8.4.4` version, so I will stay on it.

**Comment by ChristianGruen** [comment]
> That does not help at all.

I guess so ;) Feel free to talk to people on our mailing list (the guys who worked on Docker are not active here).

**Comment by TheAifam5** [comment]
Found out what is wrong. Using CLI `-c` parameter, somehow from 8.4.4< does not work as in 8.4.4 and older versions. 
As stated in the documentation:
`; Separator for multiple database commands on the command line`
my query is completely valid.

A small example of an query I do:
`basex -d -c"CREATE DB example;OPEN example;ADD /dump/example.xml;"` throws
```
org.basex.core.BaseXException: Resource "/srv/basex/;OPEN example;ADD /dump/example.xml;" not found.
        at org.basex.core.Command.execute(Command.java:94)
        at org.basex.api.client.LocalSession.execute(LocalSession.java:132)
        at org.basex.api.client.Session.execute(Session.java:36)
        at org.basex.core.CLI.execute(CLI.java:92)
        at org.basex.core.CLI.execute(CLI.java:76)
        at org.basex.core.CLI.execute(CLI.java:63)
        at org.basex.BaseX.<init>(BaseX.java:81)
        at org.basex.BaseX.main(BaseX.java:43)
Resource "/srv/basex/;OPEN example;ADD /dump/example.xml;" not found.
```

The `/srv/basex/` changes based on the working directory, in the example I am in `/src/basex`.
