### ISSUE TITLE
XQuery: Error casting arguments from xquery xslt:transform-text toward xslt params requested type

### ISSUE THREAD

**Issue by sylvainloiseau** [BaseXdb/basex#1757]
I encounter the error bellow while doing the following:

- I have a stylesheet containing:

<xsl:param name="displayphraseId" select="true()" as="xs:boolean"  />

- I try to call it using :

let $tex := xslt:transform-text($phrase, "emeld.xsl", map {"displayphraseId":'False’})

Indeed, the string ‘False’ (and not false()) is wrongly used, but this XQuery error is not properly catched if I’m correct.
Thanks,
Sylvain Loiseau

Unexpected error: Improper use? Potential bug? Your feedback is welcome:
Contact: basex-talk@mailman.uni-konstanz.de
Version: BaseX 9.1.2
Java: Oracle Corporation, 11.0.2
OS: Mac OS X, x86_64
Stack Trace: 
java.lang.IllegalArgumentException: ValidationException: The string "False" cannot be cast to a boolean
	at net.sf.saxon.jaxp.AbstractTransformerImpl.setParameter(AbstractTransformerImpl.java:203)
	at net.sf.saxon.jaxp.TransformerImpl.setParameter(TransformerImpl.java:27)
	at java.base/java.util.HashMap.forEach(HashMap.java:1336)
	at org.basex.query.func.xslt.XsltTransform.transform(XsltTransform.java:105)
	at org.basex.query.func.xslt.XsltTransform.transform(XsltTransform.java:59)
	at org.basex.query.func.xslt.XsltTransformText.item(XsltTransformText.java:16)
	at org.basex.query.expr.ParseExpr.iter(ParseExpr.java:48)
	at org.basex.query.expr.constr.Constr.add(Constr.java:70)
	at org.basex.query.expr.constr.CElem.item(CElem.java:93)
	at org.basex.query.expr.constr.CElem.item(CElem.java:1)
	at org.basex.query.expr.ParseExpr.iter(ParseExpr.java:48)
	at org.basex.query.expr.TypeCheck.iter(TypeCheck.java:87)
	at org.basex.query.scope.MainModule.iter(MainModule.java:118)
	at org.basex.query.QueryContext.iter(QueryContext.java:335)
	at org.basex.http.restxq.RestXqResponse.serialize(RestXqResponse.java:73)
	at org.basex.http.web.WebResponse.create(WebResponse.java:56)
	at org.basex.http.restxq.RestXqServlet.run(RestXqServlet.java:54)
	at org.basex.http.BaseXServlet.service(BaseXServlet.java:59)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:857)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:535)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1340)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1242)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:503)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by ChristianGruen** [comment]
It seems that Saxon throws default runtime exceptions for illegal variable assignments. Such exceptions are now caught as well.
