### ISSUE TITLE
java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by gustawdaniel** [BaseXdb/basex#1768]
I have Ubuntu 18. I typed:

```
sudo apt install basex
sudo apt install libtagsoup-java
sudo apt install libxml-commons-resolver1.1-java
sudo apt install libjing-java
```

Then I typed

```
basex
```

And got error

```
BaseX 8.5.1 [Standalone]
Try 'help' to get more information.
Exception in thread "main" java.lang.NoSuchMethodError: java.nio.ByteBuffer.limit(I)Ljava/nio/ByteBuffer;
	at jline.internal.InputStreamReader.<init>(InputStreamReader.java:104)
	at jline.console.ConsoleReader.setInput(ConsoleReader.java:330)
	at jline.console.ConsoleReader.<init>(ConsoleReader.java:248)
	at jline.console.ConsoleReader.<init>(ConsoleReader.java:236)
	at jline.console.ConsoleReader.<init>(ConsoleReader.java:224)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.basex.util.ConsoleReader$JLineConsoleReader.<init>(ConsoleReader.java:152)
	at org.basex.util.ConsoleReader.get(ConsoleReader.java:61)
	at org.basex.BaseX.console(BaseX.java:180)
	at org.basex.BaseX.<init>(BaseX.java:166)
	at org.basex.BaseX.main(BaseX.java:42)
```

How to fix it?

Additional info

```
java -version
openjdk version "11.0.5" 2019-10-15
OpenJDK Runtime Environment (build 11.0.5+10-post-Ubuntu-0ubuntu1.118.04)
OpenJDK 64-Bit Server VM (build 11.0.5+10-post-Ubuntu-0ubuntu1.118.04, mixed mode, sharing)
```

Can be connected with https://github.com/BaseXdb/basex/issues/1651

**Comment by ChristianGruen** [comment]
I assume that BaseX is not compatible with the version of jline that you installed. Can you run it without the library?

**Comment by ChristianGruen** [comment]
It seems that the error message was caused by a version of JLine (which seems to be installed on your system) and not BaseX itself. I’m now catching Errors as well; if one occurs, the default console reader is initialized. Feel free to check out the [latest stable snapshot](http://files.basex.org/releases/latest/).
