### ISSUE TITLE
java.lang.ArrayStoreException: BaseX 9.4.3 + latest

### ISSUE THREAD

**Issue by apb2006** [BaseXdb/basex#1946]
Below works in 9.3.3
```xquery
declare function local:meta($uri ) as map(*){
let $uri:=local:analyse($uri)
return  map:merge(($uri,map{"size":42}))          
};

declare function local:analyse($uri) as map(*){
  typeswitch($uri)
  case map(*) return $uri
  case xs:string return   map{   "item": "abc" }
  default return error()
};
local:meta("webfile:/ALO/gg")
```
But in 9.4
```
Improper use? Potential bug? Your feedback is welcome:
Contact: basex-talk@mailman.uni-konstanz.de
Version: BaseX 9.4.4 beta
Java: Oracle Corporation, 1.8.0_261
OS: Windows 10, amd64
Stack Trace: 
java.lang.ArrayStoreException: org.basex.query.func.fn.FnError
	at org.basex.query.InlineContext.inline(InlineContext.java:126)
	at org.basex.query.expr.Typeswitch.inline(Typeswitch.java:198)
	at org.basex.query.expr.gflwor.ForLet.inline(ForLet.java:66)
	at org.basex.query.expr.gflwor.ForLet.inline(ForLet.java:1)
	at org.basex.query.InlineContext.inlineOrNull(InlineContext.java:94)
	at org.basex.query.expr.gflwor.GFLWOR.inline(GFLWOR.java:890)
	at org.basex.query.expr.gflwor.GFLWOR.inlineLets(GFLWOR.java:339)
	at org.basex.query.expr.gflwor.GFLWOR.optimize(GFLWOR.java:107)
	at org.basex.query.func.StaticFunc.inline(StaticFunc.java:303)
	at org.basex.query.func.StaticFuncCall.compile(StaticFuncCall.java:67)
	at org.basex.query.scope.MainModule.comp(MainModule.java:81)
	at org.basex.query.QueryCompiler.compile(QueryCompiler.java:119)
	at org.basex.query.QueryCompiler.compile(QueryCompiler.java:106)
	at org.basex.query.QueryContext.compile(QueryContext.java:311)
	at org.basex.query.QueryProcessor.compile(QueryProcessor.java:79)
	at org.basex.core.cmd.AQuery.query(AQuery.java:93)
	at org.basex.core.cmd.XQuery.run(XQuery.java:22)
	at org.basex.core.Command.run(Command.java:257)
	at org.basex.core.Command.execute(Command.java:93)
	at org.basex.gui.GUI.exec(GUI.java:416)
	at org.basex.gui.GUI.lambda$4(GUI.java:359)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by ChristianGruen** [comment]
…a new snapshot is available.
