### ISSUE TITLE
archive:create-from error in BaseX 9.6+

### ISSUE THREAD

**Issue by vincentml** [BaseXdb/basex#2083]
### Description of the Problem

I attempted to migrate an existing XQuery from BaseX version 9.5 to version 9.7 and encountered a problem which I've narrowed down somewhat. Here are small self contained examples that work using BaseX version 9.5.2 and result in an error using BaseX versions 9.6 and 9.7.

```xquery
let $tempDir1 := file:create-temp-dir('basex', 'test-1')
let $tempDir2 := file:create-temp-dir('basex', 'test-2')
return (
  prof:dump($tempDir1, 'temp dir 1'),
  prof:dump($tempDir2, 'temp dir 2'),
  file:write-text($tempDir1 || 'file.txt', 'hello'),
  file:write-binary($tempDir2 || 'file.zip', archive:create-from($tempDir1))
)
```

Using BaseX 9.7 the error that is produced is this:

```
Improper use? Potential bug? Your feedback is welcome:
Contact: basex-talk@mailman.uni-konstanz.de
Version: BaseX 9.7
Java: Eclipse Adoptium, 17.0.2
OS: Windows 10, amd64
Stack Trace: 
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at org.basex.query.func.archive.ArchiveCreate.toMap(ArchiveCreate.java:165)
	at org.basex.query.func.archive.ArchiveCreate.create(ArchiveCreate.java:40)
	at org.basex.query.func.file.FileWriteBinary.write(FileWriteBinary.java:48)
	at org.basex.query.func.file.FileWriteBinary.item(FileWriteBinary.java:24)
	at org.basex.query.func.file.FileFn.item(FileFn.java:25)
	at org.basex.query.func.file.FileWriteBinary.item(FileWriteBinary.java:21)
	at org.basex.query.expr.ParseExpr.value(ParseExpr.java:51)
	at org.basex.query.expr.List.value(List.java:253)
	at org.basex.query.expr.ParseExpr.item(ParseExpr.java:56)
	at org.basex.query.expr.ItemMap.item(ItemMap.java:37)
	at org.basex.query.expr.ParseExpr.value(ParseExpr.java:51)
	at org.basex.query.expr.ParseExpr.iter(ParseExpr.java:46)
	at org.basex.query.expr.gflwor.GFLWOR$1.next(GFLWOR.java:72)
	at org.basex.query.scope.MainModule$1.next(MainModule.java:104)
	at org.basex.query.QueryContext.next(QueryContext.java:341)
	at org.basex.query.QueryContext.cache(QueryContext.java:633)
	at org.basex.query.QueryProcessor.cache(QueryProcessor.java:113)
	at org.basex.core.cmd.AQuery.query(AQuery.java:99)
	at org.basex.core.cmd.XQuery.run(XQuery.java:22)
	at org.basex.core.Command.run(Command.java:257)
	at org.basex.core.Command.execute(Command.java:93)
	at org.basex.gui.GUI.exec(GUI.java:419)
	at org.basex.gui.GUI.lambda$execute$5(GUI.java:364)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

Here is a slight variation on the query:

```xquery
let $tempDir1 := file:create-temp-dir('basex', 'test-1')
let $tempDir2 := file:create-temp-dir('basex', 'test-2')
return (
  prof:dump($tempDir1, 'temp dir 1'),
  prof:dump($tempDir2, 'temp dir 2'),
  file:write-text($tempDir1 || 'file.txt', 'hello'),
  let $zip := archive:create-from($tempDir1)
  return file:write-binary($tempDir2 || 'file.zip', $zip)
)
```

Using BaseX version 9.7 the error that is produced is "[XPTY0004] Item expected, empty sequence found." and points to line 8.

Here is another slight variation on the same query that asserts the return type of archive:create-from is as xs:base64Binary as described in the [documentation](https://docs.basex.org/wiki/Archive_Module#archive:create-from).

```xquery
let $tempDir1 := file:create-temp-dir('basex', 'test-1')
let $tempDir2 := file:create-temp-dir('basex', 'test-2')
return (
  prof:dump($tempDir1, 'temp dir 1'),
  prof:dump($tempDir2, 'temp dir 2'),
  file:write-text($tempDir1 || 'file.txt', 'hello'),
  let $zip as xs:base64Binary := archive:create-from($tempDir1)
  return file:write-binary($tempDir2 || 'file.zip', $zip)
)
```
Using BaseX version 9.7 this query produces this error: "[XPTY0004] Cannot treat empty-sequence() as xs:base64Binary: $zip." pointing to line 7.

A variation on the same query that replaces the archive:create-from function with an equivalent function works using BaseX versions 9.5.2 and 9.7 and produces the expected zip file.

```xquery
declare function local:create-from($path as xs:string) as xs:base64Binary {
  let $files := file:list($path, true())
  return archive:create($files, $files ! file:read-binary($path || .) )
};

let $tempDir1 := file:create-temp-dir('basex', 'test-1')
let $tempDir2 := file:create-temp-dir('basex', 'test-2')
return (
  prof:dump($tempDir1, 'temp dir 1'),
  prof:dump($tempDir2, 'temp dir 2'),
  file:write-text($tempDir1 || 'file.txt', 'hello'),
  file:write-binary($tempDir2 || 'file.zip', local:create-from($tempDir1))
)
```

There was a change in the archive module with BaseX version 9.6 that is shown in [this commit](https://github.com/BaseXdb/basex/commit/9f4bf4d3b8180c5fce6f25c77e186970a37c1bb5). It looks as though the problem might have been introduced in this commit.

### Expected Behavior

Using archive:create-from and file:write-binary, as shown in the examples, should create a a zip file from the contents of a directory producing the same result from the current version of BaseX as with BaseX version 9.5. 

### Steps to Reproduce the Behavior

See the examples above.

### What is your configuration?

Using BaseX 9.5, 9.6, and 9.7 running on Adoptium Java 17 on Windows 10.  

I'm using Gradle to launch specific versions of BaseX. Here is the build.gradle 

```gradle
plugins {
  id "java"
}

repositories {
  mavenCentral()
  maven {
    url "https://files.basex.org/maven"
  }
}

dependencies {
  runtimeOnly "org.basex:basex:9.5.2"
  runtimeOnly "net.sf.saxon:Saxon-HE:9.9.1-7"
}

task basex {
  description "Run BaseX GUI."
  doLast {
    ant.java(
        fork: true, 
        spawn: true, 
        classpath: configurations.runtimeClasspath.asPath, 
        classname: "org.basex.BaseXGUI",
        clonevm: true)
  }
}

defaultTasks "basex"
```

**Comment by ChristianGruen** [comment]
Thanks for the observation, Vincent. It seems the bug was old, but it was only revealed and triggered by a newer optimization.
A [new snapshot](https://files.basex.org/releases/latest/) is available.

**Comment by vincentml** [comment]
Thank you for fixing this so quickly @ChristianGruen ! I've confirmed the query is working now with the latest 9.7.1 snapshot.
